# Generated by Django 5.1.15 on 2026-04-02 09:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('APPLICATION_RECEIVED', 'Application Received'), ('APPLICATION_STATUS', 'Application Status Change'), ('JOB_MATCH', 'Job Match'), ('JOB_EXPIRING', 'Job Expiring'), ('PROFILE_VIEW', 'Profile Viewed'), ('WELCOME', 'Welcome'), ('SYSTEM', 'System')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('related_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('related_content_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
