# Generated by Django 6.0.4 on 2026-05-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('APPLICATION_RECEIVED', 'Application Received'), ('APPLICATION_STATUS', 'Application Status Change'), ('JOB_MATCH', 'Job Match'), ('JOB_EXPIRING', 'Job Expiring'), ('PROFILE_VIEW', 'Profile Viewed'), ('WELCOME', 'Welcome'), ('SYSTEM', 'System'), ('CHAT_MESSAGE', 'Chat Message')], db_index=True, max_length=30),
        ),
    ]
