# Generated by Django 5.1.15 on 2026-04-02 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experience',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.seekerprofile'),
        ),
        migrations.AddField(
            model_name='education',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='profiles.seekerprofile'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['slug'], name='profiles_sk_slug_2d9763_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category'], name='profiles_sk_categor_fcdf63_idx'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='seekers', to='profiles.skill'),
        ),
        migrations.AddIndex(
            model_name='employerprofile',
            index=models.Index(fields=['company_name'], name='profiles_em_company_51ac10_idx'),
        ),
        migrations.AddIndex(
            model_name='employerprofile',
            index=models.Index(fields=['industry'], name='profiles_em_industr_a17f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='employerprofile',
            index=models.Index(fields=['location'], name='profiles_em_locatio_5af115_idx'),
        ),
        migrations.AddIndex(
            model_name='seekerprofile',
            index=models.Index(fields=['location'], name='profiles_se_locatio_54ffea_idx'),
        ),
        migrations.AddIndex(
            model_name='seekerprofile',
            index=models.Index(fields=['experience_years'], name='profiles_se_experie_f3a8ca_idx'),
        ),
        migrations.AddIndex(
            model_name='seekerprofile',
            index=models.Index(fields=['is_open_to_work'], name='profiles_se_is_open_704241_idx'),
        ),
    ]
