# Generated by Django 4.2.29 on 2026-04-15 11:59

import apps.profiles.models
import apps.users.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(db_index=True, max_length=120, unique=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='profiles.skill')),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='ResumeParseJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('REVIEW_READY', 'Review Ready'), ('FAILED', 'Failed'), ('APPLIED', 'Applied'), ('DISCARDED', 'Discarded')], db_index=True, default='QUEUED', max_length=20)),
                ('source_file', models.FileField(upload_to=apps.profiles.models.resume_parse_source_path, validators=[apps.users.validators.validate_resume_file])),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('parser_version', models.CharField(default='v1', max_length=50)),
                ('llm_model', models.CharField(blank=True, max_length=100)),
                ('pipeline_mode', models.CharField(default='hybrid', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_applied_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_parse_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeAutofillAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('previewed', 'Previewed'), ('accepted', 'Accepted'), ('edited_before_apply', 'Edited Before Apply'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, max_length=32)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='profiles.resumeparsejob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_autofill_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileAutofillDraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='profiles.resumeparsejob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_autofill_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedResumeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('experiences', models.JSONField(blank=True, default=list)),
                ('educations', models.JSONField(blank=True, default=list)),
                ('confidence', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('raw_text', models.TextField(blank=True)),
                ('normalized_payload', models.JSONField(blank=True, default=dict)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='profiles.resumeparsejob')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='resumeparsejob',
            index=models.Index(fields=['user', 'status'], name='profiles_re_user_id_cf6815_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeparsejob',
            index=models.Index(fields=['source_hash'], name='profiles_re_source__df2868_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeautofillaudit',
            index=models.Index(fields=['user', 'action'], name='profiles_re_user_id_2e6c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeautofillaudit',
            index=models.Index(fields=['job', 'action'], name='profiles_re_job_id_3fc6fa_idx'),
        ),
        migrations.AddIndex(
            model_name='profileautofilldraft',
            index=models.Index(fields=['user', 'is_active'], name='profiles_pr_user_id_5cf651_idx'),
        ),
    ]
