# Generated by Django 4.2.29 on 2026-04-15 12:05

import apps.profiles.models
import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_skillalias_resumeparsejob_resumeautofillaudit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeparsejob',
            name='source_file',
            field=models.FileField(max_length=500, upload_to=apps.profiles.models.resume_parse_source_path, validators=[apps.users.validators.validate_resume_file]),
        ),
    ]
