# Generated by Django 5.1.15 on 2026-04-02 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='jobcategory',
            index=models.Index(fields=['slug'], name='jobs_jobcat_slug_3b5636_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcategory',
            index=models.Index(fields=['is_active'], name='jobs_jobcat_is_acti_fece89_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'created_at'], name='jobs_job_status_277b31_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_type', 'experience_level'], name='jobs_job_job_typ_33354c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location'], name='jobs_job_locatio_8b2f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['salary_min', 'salary_max'], name='jobs_job_salary__2892b4_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_featured', '-created_at'], name='jobs_job_is_feat_e3be6a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['employer', 'status'], name='jobs_job_employe_9a6de3_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-views_count'], name='jobs_job_views_c_b8de09_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['slug'], name='jobs_job_slug_9562d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(check=models.Q(('salary_min__lte', models.F('salary_max')), ('salary_min__isnull', True), ('salary_max__isnull', True), _connector='OR'), name='salary_min_lte_max'),
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('user', 'job')},
        ),
    ]
