# Generated by Django 6.0.4 on 2026-05-18 03:49

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_search_vector'),
        ('profiles', '0004_alter_resumeparsejob_source_file'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='idx_job_search_vector'),
        ),
    ]
