# Generated by Django 6.0.4 on 2026-05-18 03:49

import apps.applications.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
        ('jobs', '0004_job_search_vector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetterDraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_hash', models.CharField(db_index=True, max_length=64)),
                ('cover_letter', models.TextField(max_length=10000)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('generator', models.CharField(choices=[('template', 'Template'), ('llm', 'LLM')], default='template', max_length=20)),
                ('llm_model', models.CharField(blank=True, max_length=100)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(db_index=True, default=apps.applications.models._default_cover_letter_expires)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letter_drafts', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letter_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoverLetterAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('previewed', 'Previewed'), ('generated', 'Generated'), ('edited_before_apply', 'Edited Before Apply'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, max_length=32)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letter_audits', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letter_audits', to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='applications.coverletterdraft')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coverletterdraft',
            index=models.Index(fields=['user', 'job', 'profile_hash'], name='application_user_id_26310d_idx'),
        ),
        migrations.AddIndex(
            model_name='coverletterdraft',
            index=models.Index(fields=['user', 'job', '-created_at'], name='application_user_id_2224a9_idx'),
        ),
        migrations.AddIndex(
            model_name='coverletteraudit',
            index=models.Index(fields=['user', 'action'], name='application_user_id_f604e8_idx'),
        ),
        migrations.AddIndex(
            model_name='coverletteraudit',
            index=models.Index(fields=['job', 'action'], name='application_job_id_9ba917_idx'),
        ),
    ]
